[BUG] Fixed Player Freeze in Vehicle
tabarra/txAdmin pull request #464
Opened 2021-10-10 15:53 UTC by tim-it-ger

- added disable 'f' if a player is in a vehicle. to prevent the player to leave the vehicle.

fix for issue: #463

2021-10-10 15:59 UTC, ghost commented
You can bypass this by setting another key as leave vehicle or use an controller

2021-10-10 16:46 UTC, LiamDormon commented on scripts/menu/client/cl_freeze.lua
> +     DisableControlAction(0, 23, isFrozen)
This native would need to be ran every frame.

2021-10-10 18:42 UTC, tim-it-ger commented on scripts/menu/client/cl_freeze.lua
> +     DisableControlAction(0, 23, isFrozen)
if the player use a Mod Menu yes.
but 1 execution is enough

2021-10-11 11:37 UTC, NoobKeksTV commented on scripts/menu/client/cl_freeze.lua
> +     DisableControlAction(0, 23, isFrozen)
Instead of blocking the key, just disable movement for Ped & car hes in, if hes the driver. 

This way he cant move at all. He can exit, yes. but cant move.

2021-10-11 11:38 UTC, NoobKeksTV requested changes
instead of permanently disablying control, just FreezeEntity of PEd & car if hes the driver.  this way he cant move at all. he can exit but not move.

2021-10-23 06:40 UTC, TasoOneAsia commented
Thanks for the PR but the logic present in #466 makes more sense for this use case.

2021-10-23 06:40 UTC, closed without merging