fix(client/freeze): exit vehicle
tabarra/txAdmin pull request #466
Opened 2021-10-10 18:04 UTC by Jaccosf

- In my opinion, the best way to do this is let the player leave the vehicle (the vehicle will also stop, if the driver is being freezed) and freeze it after.

2021-10-10 18:05 UTC, Jaccosf commented
This will be a fix for: #463

2021-10-11 11:43 UTC, ZockerBoysHD commented
yeah, this should work. 
#464 is not the right way, it would have to be run in a thread to be called every frame but this makes the ped leave any vehicle hes in so we can freeze him properly. 
Also we could just freeze the Player and the car both but as mentioned by tab in #463 that will require a check for the car when player gets unfreezed.

This gets approval by NoobKeks Pro dev 👍

2021-10-11 12:02 UTC, Jaccosf commented
Haha thanks! 😃

2021-10-12 19:40 UTC, TasoOneAsia requested changes

2021-10-12 19:40 UTC, TasoOneAsia commented on scripts/menu/client/cl_freeze.lua
> +    TaskLeaveAnyVehicle(playerPed)
Can we pass a flag of `16` to the optional flags please. This flag specifically specifies teleport outside of the vehicle immediately.

[Ref](https://docs.fivem.net/natives/?_0xD3DBCE61A490BE02)

2021-10-12 19:44 UTC, Jaccosf commented on scripts/menu/client/cl_freeze.lua
> +    TaskLeaveAnyVehicle(playerPed)
Yeah sure

2021-10-23 06:38 UTC, TasoOneAsia commented
I think the overall logic is this implementation is sound, I'll slate it for testing tomorrow, thanks for the patience.

2021-10-23 18:50 UTC, merged